name: Deploying to Firebase

on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        check-latest: true'

    - name: Install Dependencies
      run: npm install

    - name: Globally install Angular CLI
      run: npm i -g @angular/cli

    - name: Build site for production
      run: ng build --prod

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
